---
# Global variables for all hosts
ansible_user: ansible
ansible_ssh_private_key_file: ~/.ssh/id_rsa
ansible_python_interpreter: /usr/bin/python3

# Application settings
app_name: myapp
app_port: 8000
app_user: appuser
app_group: appuser

# Common system settings
system_timezone: UTC
log_level: info

# Security settings
ssh_allow_password_auth: false
ssh_permit_root_login: false

# Backup settings
backup_retention_days: 30
backup_schedule: "0 2 * * *"