---
# Ansible Collections
collections:
  - name: community.general
    version: ">=7.0.0"
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.crypto
    version: ">=2.0.0"
  - name: community.postgresql
    version: ">=2.0.0"
  - name: community.mysql
    version: ">=3.0.0"
  - name: community.docker
    version: ">=3.0.0"
  - name: kubernetes.core
    version: ">=2.4.0"

# Ansible Galaxy Roles
roles:
  - name: geerlingguy.nginx
    version: ">=4.0.0"
  - name: geerlingguy.postgresql
    version: ">=3.0.0"
  - name: geerlingguy.redis
    version: ">=1.8.0"
  - name: geerlingguy.docker
    version: ">=6.0.0"
  - name: geerlingguy.security
    version: ">=2.0.0"
  - name: geerlingguy.firewall
    version: ">=2.0.0"
  - name: cloudalchemy.prometheus
    version: ">=3.0.0"
  - name: cloudalchemy.grafana
    version: ">=1.0.0"