---
all:
  children:
    web:
      hosts:
        web01-staging.example.com:
          ansible_host: 10.0.2.10
      vars:
        env: staging
    db:
      hosts:
        db01-staging.example.com:
          ansible_host: 10.0.2.20
      vars:
        env: staging
    lb:
      hosts:
        lb01-staging.example.com:
          ansible_host: 10.0.2.30
      vars:
        env: staging