---
- name: Update system packages
  package:
    update_cache: yes
  when: ansible_os_family in ['Debian', 'RedHat']

- name: Install common packages
  package:
    name: "{{ common_packages }}"
    state: present

- name: Create application user
  user:
    name: "{{ app_user }}"
    system: yes
    shell: /bin/bash
    home: "/home/{{ app_user }}"
    create_home: yes

- name: Configure timezone
  timezone:
    name: "{{ system_timezone }}"
  notify: restart cron

- name: Configure NTP
  package:
    name: ntp
    state: present
  notify: restart ntp