---
all:
  children:
    web:
      hosts:
        web01.example.com:
          ansible_host: 10.0.1.10
        web02.example.com:
          ansible_host: 10.0.1.11
      vars:
        env: production
    db:
      hosts:
        db01.example.com:
          ansible_host: 10.0.1.20
        db02.example.com:
          ansible_host: 10.0.1.21
      vars:
        env: production
    lb:
      hosts:
        lb01.example.com:
          ansible_host: 10.0.1.30
      vars:
        env: production