---
all:
  children:
    web:
      hosts:
        web01-dev.example.com:
          ansible_host: 192.168.1.10
      vars:
        env: development
    db:
      hosts:
        db01-dev.example.com:
          ansible_host: 192.168.1.20
      vars:
        env: development