---
- name: System maintenance tasks
  hosts: all
  become: yes
  tasks:
    - name: Update package cache
      package:
        update_cache: yes
      when: ansible_os_family in ['Debian', 'RedHat']

    - name: Check disk usage
      shell: df -h
      register: disk_usage
      changed_when: false

    - name: Display disk usage
      debug:
        var: disk_usage.stdout_lines

    - name: Clean package cache
      package:
        autoremove: yes
      when: ansible_os_family == 'Debian'

    - name: Check system uptime
      shell: uptime
      register: system_uptime
      changed_when: false

    - name: Display system uptime
      debug:
        var: system_uptime.stdout