---
- name: Configure web servers
  hosts: web
  become: yes
  roles:
    - common
    - nginx
    - application

- name: Configure database servers
  hosts: db
  become: yes
  roles:
    - common
    - database

- name: Configure load balancers
  hosts: lb
  become: yes
  roles:
    - common
    - loadbalancer